export const CART_ADD_ITEM = 'CART_ADD_ITEM'
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM'


export const SAVE_CART_SHIPPING_ADDRESS = 'SAVE_CART_SHIPPING_ADDRESS'
export const SAVE_CART_PAYMENT_METHOD = 'SAVE_CART_PAYMENT_METHOD'


